export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  embeddingApiKey: process.env.OPENAI_API_KEY ?? "",
  embeddingApiBaseUrl: process.env.OPENAI_EMBEDDING_BASE_URL ?? "https://api.openai.com",
  embeddingModel: process.env.OPENAI_EMBEDDING_MODEL ?? "text-embedding-3-small",
  miraV3Enabled: process.env.MIRA_V3_ENABLED === "true",
  miraV3BirthDataEnabled: process.env.MIRA_V3_BIRTH_DATA_ENABLED === "true",
  dakidartsApiKey: process.env.DAKIDARTS_API_KEY ?? "",
  dakidartsApiBaseUrl: process.env.DAKIDARTS_API_BASE_URL ?? "https://api.numerologyapi.com/api/v1",
  notionIntelligenceEnabled: process.env.NOTION_INTELLIGENCE_ENABLED === "true",
  notionApiKey: process.env.NOTION_API_KEY ?? "",
  notionDatabaseId: process.env.NOTION_DATABASE_ID ?? "",
  notionApiBaseUrl: process.env.NOTION_API_BASE_URL ?? "https://api.notion.com",
  devLocalAuthBypass: process.env.DEV_LOCAL_AUTH_BYPASS === "true",
  devLocalOpenId: process.env.DEV_LOCAL_OPEN_ID ?? "local-dev-mira-user",
  miraLocalFileStore: process.env.MIRA_LOCAL_FILE_STORE === "true",
  paymentMode: (process.env.MIRA_PAYMENT_MODE ?? (process.env.NODE_ENV === "production" ? "stripe" : "local")) as "local" | "stripe",
  stripePaymentLinkUrl: process.env.STRIPE_PAYMENT_LINK_URL ?? "",
  stripeSecretKey: process.env.STRIPE_SECRET_KEY ?? "",
  stripeWebhookSecret: process.env.MIRA_STRIPE_WEBHOOK_SECRET ?? process.env.STRIPE_WEBHOOK_SECRET ?? "",
  stripePriceId: process.env.STRIPE_PRICE_ID ?? "",
  stripeCurrency: process.env.STRIPE_CURRENCY ?? "eur",
  emailWorkerSecret: process.env.MIRA_EMAIL_WORKER_SECRET ?? "",
  invitationLinkSecret: process.env.MIRA_INVITATION_LINK_SECRET ?? "",
  emailProvider: process.env.MIRA_EMAIL_PROVIDER ?? "",
  resendApiKey: process.env.RESEND_API_KEY ?? "",
  invitationFrom: process.env.MIRA_INVITATION_FROM ?? "",
  publicAppBaseUrl: process.env.MIRA_PUBLIC_APP_BASE_URL ?? "",
  openAiRealtimeModel: process.env.OPENAI_REALTIME_MODEL ?? "gpt-realtime-2.1",
  openAiRealtimeVoice: process.env.OPENAI_REALTIME_VOICE ?? "marin",
  openAiRealtimeCustomVoiceId: process.env.OPENAI_REALTIME_CUSTOM_VOICE_ID?.trim() ?? "",
  openAiRealtimeTranscriptionModel: process.env.OPENAI_REALTIME_TRANSCRIPTION_MODEL ?? "gpt-4o-mini-transcribe",
  miraPilotQaRetentionDays: Number.parseInt(process.env.MIRA_PILOT_QA_RETENTION_DAYS ?? "7", 10),
};
