export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  embeddingApiKey: process.env.OPENAI_API_KEY ?? "",
  embeddingApiBaseUrl: process.env.OPENAI_EMBEDDING_BASE_URL ?? "https://api.openai.com",
  embeddingModel: process.env.OPENAI_EMBEDDING_MODEL ?? "text-embedding-3-small",
  miraV3Enabled: process.env.MIRA_V3_ENABLED === "true",
  miraV3BirthDataEnabled: process.env.MIRA_V3_BIRTH_DATA_ENABLED === "true",
  dakidartsApiKey: process.env.DAKIDARTS_API_KEY ?? "",
  dakidartsApiBaseUrl: process.env.DAKIDARTS_API_BASE_URL ?? "https://api.numerologyapi.com/api/v1",
  notionIntelligenceEnabled: process.env.NOTION_INTELLIGENCE_ENABLED === "true",
  notionApiKey: process.env.NOTION_API_KEY ?? "",
  notionDatabaseId: process.env.NOTION_DATABASE_ID ?? "",
  notionApiBaseUrl: process.env.NOTION_API_BASE_URL ?? "https://api.notion.com",
  devLocalAuthBypass: process.env.DEV_LOCAL_AUTH_BYPASS === "true",
  devLocalOpenId: process.env.DEV_LOCAL_OPEN_ID ?? "local-dev-mira-user",
};
